<?php $title = 'Ways To Earn'; ?>

@extends('content.templates.default')

@section('content')
    {{ ViewHelper::getNewBreadcrumbs(null, 'Earn Money') }}

    <h1 class="page-header">Overview</h1>
    <p class="lead">
        At DiscoverCooks, we use a revenue sharing model which pays our users the majority of the revenue we make. We share our revenue with our content creators because they are the ones responsible for our sites success and we think it's only fair that they share in the rewards.
    </p>
    <p>
        As of right now, you are able to earn your money from both recipes and reviews you create. We have plans to include other ways to earn in the future and they will be announced at a later date.
    </p>
    <p>
        Every week, a credit will be posted to your account based on the revenue generated by the site and the performance of both your recipes and reviews. Once you've passed the minimum threshold to withdraw, currently $15.00, you'll be able to request a payout. We currently use paypal as our payout solution but are looking into more options.
    </p>

    <h1 class="page-header" id="ways-to-earn">Ways To Earn</h1>

    <h3>Recipes</h3>

    <p>
        Earn money by creating recipes and getting them seen by others. Each unique hit on your recipes creates a page view. At the end of every week, we take the total pages views that your recipes generated and divide it by the total page views of the site. We then use that number and multiply it by the total revenue the site made for the week. Then we multiply that by a factor which varies based on your status with the site. Currently, all members joining the site until June 30, 2015 will have a minimum factor of 80% for the lifetime of their account.
    </p>
    <p>
        To put it in simpler terms, new members until June 30, 2015 will earn <strong>80%</strong> of the revenue their pages generate. New members lock in this percentage for the lifetime of their account, and while it may change and go up in the future, it will never go lower.
    </p>

    <h3>Reviews</h3>

    <p>
        Earn money by reviewing recipes. Each review you make has the potential to get upvotes and downvotes based on the quality of the review.
    </p>

    <p>
        At the end of each week, we tally up the total upvotes and downvotes. We use the net upvotes as well as your net upvotes for the week to determine how many of the net upvotes were caused by your reviews. This percentage is multiplied by the 10% of the total revenue the site earns.
    </p>

    <p>
        In simpler terms, reviews found helpful from other users earn a part of <strong>10%</strong> of the total site revenue based on their helpfulness compared to other reviews helpfulness.
    </p>

    <h1 class="page-header" id="faq">FAQ</h1>

    <p>
        <strong>
            Where can I check my balance?
        </strong>
    </p>
    <p>
        To see your balance you must be first logged in. Select 'My Account' from the Main Menu near the top of the screen.
    </p>

    <p>
        <strong>
            How can I request payment?
        </strong>
    </p>
    <p>
        You must first be logged in. Go to 'My Account' and select 'Payments Center'. From there you will be able to request a payment. Please note you must have an account balance of at least $15.00 to request a payment at this time.
    </p>

    <p>
        <strong>
            When can my account start earning money?
        </strong>
    </p>
    <p>
        You are eligible to earn immediately upon registering.
    </p>

    <p>
        <strong>
            There is a problem with my account. What should I do?
        </strong>
    </p>
    <p>
        If you are able to access your account and are having problems, please post on our Support Forum. If you are unable to access your account, please <a href="{{ url('contact') }}">Contact Us</a>.
    </p>

    <p>
        <strong>
            I have a question that was not asked here.
        </strong>
    </p>
    <p>
        We are sorry for the inconvenience. Please feel free to ask your question on the <a href="{{ url('forum') }}">Forum</a> or <a href="{{ url('contact') }}">Contact Us</a>.
    </p>
@stop